### PR TITLE
added calculator

### PR DESCRIPTION
**Pull request by akadeepesh**

### CODE REVIEW

**Comment by ayushichoudhary-19** [comment]
@akadeepesh Please attach screenshots.

**Comment by akadeepesh** [comment]
Added

**Comment by akadeepesh** [comment]
image

**Comment by ayushichoudhary-19** [comment]
In reviewing your pull request, I noticed that the main logic of the code has been commented out, and the changes have transformed the original statistical calculator into a general-purpose calculator. However, the project's requirement is to maintain its focus on statistical calculations.

To align with the project's scope, I suggest the following:

1. Introduce a keyboard interface with buttons only for: numbers, AC (All Clear), Del (Delete), Submit, and comma.

2. Reapply the original statistical calculation logic to this interface.

This will ensure that our project remains in line with its intended purpose and functionality. Please make the necessary adjustments and resubmit your pull request. Thank you!

**Pull request closed without merging**
